# Generated by Django 4.2.25 on 2025-11-06 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="Git username for local tracking",
                        max_length=150,
                        null=True,
                    ),
                ),
                ("action", models.CharField(db_index=True, max_length=100)),
                ("resource_type", models.CharField(max_length=50)),
                ("resource_id", models.CharField(db_index=True, max_length=100)),
                ("details", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
