# Generated by Django 4.2.25 on 2025-11-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndexedItem",
            fields=[
                (
                    "id",
                    models.CharField(
                        help_text="ULID",
                        max_length=26,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("prompt", "Prompt"),
                            ("template", "Template"),
                            ("chat", "Chat"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True, default="")),
                ("slug", models.CharField(max_length=200)),
                (
                    "labels_json",
                    models.TextField(default="[]", help_text="JSON array of labels"),
                ),
                ("author", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(db_index=True)),
                ("version_count", models.IntegerField(default=0)),
                (
                    "head_version_id",
                    models.CharField(blank=True, max_length=26, null=True),
                ),
                (
                    "head_version_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("file_path", models.CharField(max_length=500)),
                ("sha", models.CharField(default="latest", max_length=64)),
                ("provider", models.CharField(blank=True, max_length=100, null=True)),
                ("model", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "conversation_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("turn_count", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "indexed_items",
                "ordering": ["-updated_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["item_type", "-updated_at", "-id"],
                        name="idx_type_updated",
                    ),
                    models.Index(fields=["item_type", "slug"], name="idx_type_slug"),
                    models.Index(fields=["author"], name="idx_author"),
                    models.Index(fields=["provider"], name="idx_provider"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="indexeditem",
            constraint=models.UniqueConstraint(
                fields=("item_type", "slug"), name="unique_type_slug"
            ),
        ),
    ]
